
.include "viaDot.mk"
sinclude "I do not exist."
-include "I, too, do not exist."
-include *.mk
include viaDot.* # Tests globbing...

all:
	echo $(ANOTHER_FILE) | grep -F True
	echo $(VIA_DOT) | grep -F True